name = "muse-wear"
pages_build_output_dir = "./out"
compatibility_date = "2024-12-01"

[[d1_databases]]
binding = "DB"
database_name = "muse-wear"
database_id = "ae75bf67-c55f-4df9-bb51-010767871efa"
