interface Env { DB: D1Database }
interface D1Database { prepare(sql: string): D1PreparedStatement }
interface D1PreparedStatement { bind(...values: unknown[]): D1PreparedStatement; first<T = unknown>(): Promise<T | null>; all<T = unknown>(): Promise<{ results: T[] }>; run(): Promise<unknown> }
interface PagesContext { request: Request; env: Env; params: Record<string, string | string[] | undefined> }
interface AppUser { id: string; email: string; full_name: string; role: "customer" | "employee" | "admin"; created_at: string }

const json = (data: unknown, status = 200, extraHeaders: Record<string, string> = {}) => new Response(JSON.stringify(data), { status, headers: { "content-type": "application/json", "cache-control": "no-store", ...extraHeaders } });
const id = () => crypto.randomUUID();
const cookie = (name: string, value: string, maxAge: number) => `${name}=${value}; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=${maxAge}`;
const parseCookies = (request: Request) => Object.fromEntries((request.headers.get("cookie") || "").split(";").map((part) => part.trim().split("=")).filter(([key, value]) => key && value));

function b64(bytes: Uint8Array) { return btoa(String.fromCharCode(...bytes)); }
function unb64(value: string) { return Uint8Array.from(atob(value), (char) => char.charCodeAt(0)); }
async function hash(password: string) { const salt = crypto.getRandomValues(new Uint8Array(16)); const key = await crypto.subtle.importKey("raw", new TextEncoder().encode(password), "PBKDF2", false, ["deriveBits"]); const bits = await crypto.subtle.deriveBits({ name: "PBKDF2", salt, iterations: 210000, hash: "SHA-256" }, key, 256); return `pbkdf2_sha256$210000$${b64(salt)}$${b64(new Uint8Array(bits))}`; }
async function verify(password: string, stored: string) { const [scheme, count, salt, expected] = stored.split("$"); if (scheme !== "pbkdf2_sha256") return false; const key = await crypto.subtle.importKey("raw", new TextEncoder().encode(password), "PBKDF2", false, ["deriveBits"]); const bits = await crypto.subtle.deriveBits({ name: "PBKDF2", salt: unb64(salt), iterations: Number(count), hash: "SHA-256" }, key, 256); return b64(new Uint8Array(bits)) === expected; }
async function user(request: Request, env: Env) { const session = parseCookies(request).muse_session; if (!session) return null; return env.DB.prepare("SELECT u.id, u.email, u.full_name, u.role, u.created_at FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.id=? AND s.expires_at > datetime('now')").bind(session).first<AppUser>(); }
async function body(request: Request) { try { return await request.json() as Record<string, unknown>; } catch { return {}; } }
function product(row: Record<string, unknown>) { const list = (key: string) => { try { return JSON.parse(String(row[key] || "[]")); } catch { return []; } }; const images = list("images"); return { id: row.id, nameEn: row.title, nameAr: row.title, brand: row.brand, category: row.category_slug, subcategory: row.category_name, price: Number(row.sale_price ?? row.price), originalPrice: row.sale_price == null ? undefined : Number(row.price), image: images[0] || "/mw-mark.svg", images, colors: list("colors"), sizes: list("sizes"), isNew: Boolean(row.is_new), isMuseMade: Boolean(row.is_muse_made), stockQty: Number(row.stock_qty), sku: row.sku }; }

export const onRequest = async ({ request, env, params }: PagesContext) => {
  const path = Array.isArray(params.path) ? params.path.join("/") : String(params.path || "");
  if (path === "auth/me" && request.method === "GET") return json({ user: await user(request, env) });
  if (path === "auth/logout" && request.method === "POST") { const session = parseCookies(request).muse_session; if (session) await env.DB.prepare("DELETE FROM sessions WHERE id=?").bind(session).run(); return new Response(null, { status: 204, headers: { "set-cookie": cookie("muse_session", "", 0) } }); }
  if (path === "auth/signup" && request.method === "POST") { const data = await body(request); const email = String(data.email || "").trim().toLowerCase(); const name = String(data.fullName || "").trim(); const password = String(data.password || ""); if (!name || !/^\S+@\S+\.\S+$/.test(email) || password.length < 8 || !/[A-Z]/.test(password) || !/[0-9]/.test(password)) return json({ error: "Enter a name, valid email, and password with 8+ characters, a capital letter, and a number." }, 400); try { const uid = id(); await env.DB.prepare("INSERT INTO users (id,email,password_hash,full_name) VALUES (?,?,?,?)").bind(uid, email, await hash(password), name).run(); const sid = id(); await env.DB.prepare("INSERT INTO sessions (id,user_id,expires_at) VALUES (?, ?, datetime('now','+30 days'))").bind(sid, uid).run(); return json({ user: { id: uid, email, full_name: name, role: "customer" } }, 201, { "set-cookie": cookie("muse_session", sid, 2592000) }); } catch { return json({ error: "Email already registered." }, 409); } }
  if (path === "auth/login" && request.method === "POST") { const data = await body(request); const found = await env.DB.prepare("SELECT * FROM users WHERE email=?").bind(String(data.email || "").trim().toLowerCase()).first<Record<string, unknown>>(); if (!found || !(await verify(String(data.password || ""), String(found.password_hash)))) return json({ error: "Invalid email or password." }, 401); const sid = id(); await env.DB.prepare("INSERT INTO sessions (id,user_id,expires_at) VALUES (?, ?, datetime('now','+30 days'))").bind(sid, found.id).run(); await env.DB.prepare("UPDATE users SET last_login_at=datetime('now') WHERE id=?").bind(found.id).run(); return json({ user: { id: found.id, email: found.email, full_name: found.full_name, role: found.role, created_at: found.created_at } }, 200, { "set-cookie": cookie("muse_session", sid, 2592000) }); }
  if (path === "products" && request.method === "GET") { const rows = await env.DB.prepare("SELECT p.*, c.name category_name, c.slug category_slug FROM products p LEFT JOIN categories c ON c.id=p.category_id WHERE p.is_active=1 ORDER BY p.created_at DESC").all<Record<string, unknown>>(); return json({ products: rows.results.map(product) }); }
  if (path === "products" && ["POST", "PUT", "DELETE"].includes(request.method)) { const current = await user(request, env); if (!current || current.role !== "admin") return json({ error: "Admin access required." }, 403); const data = await body(request); if (request.method === "POST") { const productId = id(); await env.DB.prepare("INSERT INTO products (id,title,description,brand,category_id,price,sale_price,sku,stock_qty,images,colors,sizes,is_new,is_muse_made) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?)").bind(productId, data.title, data.description || "", data.brand, data.categoryId || null, data.price, data.salePrice || null, data.sku, data.stockQty || 0, JSON.stringify(data.images || []), JSON.stringify(data.colors || []), JSON.stringify(data.sizes || []), data.isNew ? 1 : 0, data.isMuseMade ? 1 : 0).run(); return json({ id: productId }, 201); } const productId = String(data.id || ""); if (request.method === "DELETE") await env.DB.prepare("UPDATE products SET is_active=0, updated_at=datetime('now') WHERE id=?").bind(productId).run(); else await env.DB.prepare("UPDATE products SET title=?,description=?,brand=?,price=?,sale_price=?,sku=?,stock_qty=?,images=?,updated_at=datetime('now') WHERE id=?").bind(data.title, data.description || "", data.brand, data.price, data.salePrice || null, data.sku, data.stockQty || 0, JSON.stringify(data.images || []), productId).run(); return json({ ok: true }); }
  if (path === "timeclock" && request.method === "GET") { const current = await user(request, env); if (!current || current.role === "customer") return json({ error: "Employee access required." }, 403); const rows = await env.DB.prepare("SELECT * FROM timesheets WHERE user_id=? ORDER BY clock_in DESC LIMIT 30").bind(current.id).all(); return json({ entries: rows.results }); }
  if (path === "timeclock" && request.method === "POST") { const current = await user(request, env); if (!current || current.role === "customer") return json({ error: "Employee access required." }, 403); const open = await env.DB.prepare("SELECT id FROM timesheets WHERE user_id=? AND clock_out IS NULL").bind(current.id).first<{ id: string }>(); if (open) await env.DB.prepare("UPDATE timesheets SET clock_out=datetime('now') WHERE id=?").bind(open.id).run(); else await env.DB.prepare("INSERT INTO timesheets (id,user_id,clock_in) VALUES (?, ?, datetime('now'))").bind(id(), current.id).run(); return json({ ok: true }); }
  return json({ error: "Not found" }, 404);
};
